### ISSUE TITLE
Query Examples

### ISSUE THREAD

**Issue by Itopian** [dxnn/dagoba#1]
Greetings,

Just get started with the lib to use as a backend for a graph visualization interface.  Will be writing queries to return results that can be visualized.  Reading through the documentation and running the example / tests, it looks like the queries only return the nodes, but not the edges.  Can you provide an example of running a query such that the results provide the nodes and edges for the entire path?  In other words, if search is get parent and its children (2), I would expect a return of three nodes and two edges.

Thanks for your assistance!  Great work!!!

**Comment by dxnn** [comment]
Hi JBatUN, thanks for the note! 

As you discovered, the current query system is focused around collecting nodes, and doesn't return the set of edges followed to find those nodes. (In fact, any edges that match the query are consumed as the query is being processed.)

I think it would be very interesting to develop a subgraph-based graph database, which could return both nodes and edges from the matching subgraph(s). As far as I know no one has pursued this approach, but it is a natural fit to a variety of graph queries. 

In the meantime, I'd suggest either modelling the data so that the values you need are all in the nodes, or running a small post-processing step to "fill in" the missing edges between nodes (since in cases like the one you describe this is relatively trivial).
